# Generated by Django 5.2.7 on 2026-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_location_route_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='routes/'),
        ),
    ]
